/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Member,
  ResponseGetDrinksForEventMembersMemberIdDrinksGet,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MemberFromJSON,
    MemberToJSON,
    ResponseGetDrinksForEventMembersMemberIdDrinksGetFromJSON,
    ResponseGetDrinksForEventMembersMemberIdDrinksGetToJSON,
} from '../models/index';

export interface GetDrinksForEventMembersMemberIdDrinksGetRequest {
    memberId: number;
    grouped?: boolean;
}

/**
 * 
 */
export class MembersApi extends runtime.BaseAPI {

    /**
     * Get Drinks For Event
     */
    async getDrinksForEventMembersMemberIdDrinksGetRaw(requestParameters: GetDrinksForEventMembersMemberIdDrinksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseGetDrinksForEventMembersMemberIdDrinksGet>> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling getDrinksForEventMembersMemberIdDrinksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['grouped'] != null) {
            queryParameters['grouped'] = requestParameters['grouped'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/members/{member_id}/drinks`.replace(`{${"member_id"}}`, encodeURIComponent(String(requestParameters['memberId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseGetDrinksForEventMembersMemberIdDrinksGetFromJSON(jsonValue));
    }

    /**
     * Get Drinks For Event
     */
    async getDrinksForEventMembersMemberIdDrinksGet(requestParameters: GetDrinksForEventMembersMemberIdDrinksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseGetDrinksForEventMembersMemberIdDrinksGet> {
        const response = await this.getDrinksForEventMembersMemberIdDrinksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Members
     */
    async membersMembersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Member>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/members`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MemberFromJSON));
    }

    /**
     * Members
     */
    async membersMembersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Member>> {
        const response = await this.membersMembersGetRaw(initOverrides);
        return await response.value();
    }

}
