from .member import get_member_repository, CRUDMember
from .event import get_event_repository, CRUDEvent
from .quote import get_quote_repository, CRUDQuote
from .quote_rotation import get_quote_rotation_repository, CRUDQuoteRotation
from .auth import get_auth_repository, CRUDAuth
from .drink import get_drink_repository, CRUDDrink
from .chug import get_chug_repository, CRUDChug
from .card import get_card_repository, CRUDCard
from .recipe import get_recipe_repository, CRUDRecipe
