from .member import get_member_repository, CRUDMember
from .event import get_event_repository, CRUDEvent
from .quote import get_quote_repository, CRUDQuote
from .quote_rotation import get_quote_rotation_repository, CRUDQuoteRotation
from .auth import get_auth_repository, CRUDAuth
from .drink import get_drink_repository, CRUDDrink
from .chug import get_chug_repository, CRUDChug
from .card import get_card_repository, CRUDCard
from .recipe import get_recipe_repository, CRUDRecipe
from .calendar import get_calendar_link_repository, CRUDCalendarLink
from .kicker import get_kicker_match_repository, CRUDKickerMatch
from .dates import get_date_idea_repository, CRUDDateIdea
