apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: aperol-backend-ingress
  namespace: aperol
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`api.aperol.life`)
    kind: Rule
    services:
    - name: backend-service
      port: 80
  tls:
    certResolver: letsencrypt