/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Member } from './Member';
import {
    MemberFromJSON,
    MemberFromJSONTyped,
    MemberToJSON,
    MemberToJSONTyped,
} from './Member';

/**
 * 
 * @export
 * @interface BaseChug
 */
export interface BaseChug {
    /**
     * 
     * @type {Member}
     * @memberof BaseChug
     */
    member: Member;
    /**
     * 
     * @type {number}
     * @memberof BaseChug
     */
    time: number;
}

/**
 * Check if a given object implements the BaseChug interface.
 */
export function instanceOfBaseChug(value: object): value is BaseChug {
    if (!('member' in value) || value['member'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    return true;
}

export function BaseChugFromJSON(json: any): BaseChug {
    return BaseChugFromJSONTyped(json, false);
}

export function BaseChugFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseChug {
    if (json == null) {
        return json;
    }
    return {
        
        'member': MemberFromJSON(json['member']),
        'time': json['time'],
    };
}

  export function BaseChugToJSON(json: any): BaseChug {
      return BaseChugToJSONTyped(json, false);
  }

  export function BaseChugToJSONTyped(value?: BaseChug | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member': MemberToJSON(value['member']),
        'time': value['time'],
    };
}

