/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCard
 */
export interface CreateCard {
    /**
     * 
     * @type {number}
     * @memberof CreateCard
     */
    memberId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCard
     */
    cardUid: string;
}

/**
 * Check if a given object implements the CreateCard interface.
 */
export function instanceOfCreateCard(value: object): value is CreateCard {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('cardUid' in value) || value['cardUid'] === undefined) return false;
    return true;
}

export function CreateCardFromJSON(json: any): CreateCard {
    return CreateCardFromJSONTyped(json, false);
}

export function CreateCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCard {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['member_id'],
        'cardUid': json['card_uid'],
    };
}

  export function CreateCardToJSON(json: any): CreateCard {
      return CreateCardToJSONTyped(json, false);
  }

  export function CreateCardToJSONTyped(value?: CreateCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member_id': value['memberId'],
        'card_uid': value['cardUid'],
    };
}

