/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';
import type { Member } from './Member';
import {
    MemberFromJSON,
    MemberFromJSONTyped,
    MemberToJSON,
    MemberToJSONTyped,
} from './Member';

/**
 * 
 * @export
 * @interface Drink
 */
export interface Drink {
    /**
     * 
     * @type {string}
     * @memberof Drink
     */
    drink: string;
    /**
     * 
     * @type {number}
     * @memberof Drink
     */
    mlAlc: number;
    /**
     * 
     * @type {number}
     * @memberof Drink
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Drink
     */
    time: Date;
    /**
     * 
     * @type {Member}
     * @memberof Drink
     */
    consumer: Member;
    /**
     * 
     * @type {Event}
     * @memberof Drink
     */
    event: Event;
}

/**
 * Check if a given object implements the Drink interface.
 */
export function instanceOfDrink(value: object): value is Drink {
    if (!('drink' in value) || value['drink'] === undefined) return false;
    if (!('mlAlc' in value) || value['mlAlc'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('consumer' in value) || value['consumer'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function DrinkFromJSON(json: any): Drink {
    return DrinkFromJSONTyped(json, false);
}

export function DrinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Drink {
    if (json == null) {
        return json;
    }
    return {
        
        'drink': json['drink'],
        'mlAlc': json['ml_alc'],
        'id': json['id'],
        'time': (new Date(json['time'])),
        'consumer': MemberFromJSON(json['consumer']),
        'event': EventFromJSON(json['event']),
    };
}

  export function DrinkToJSON(json: any): Drink {
      return DrinkToJSONTyped(json, false);
  }

  export function DrinkToJSONTyped(value?: Drink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'drink': value['drink'],
        'ml_alc': value['mlAlc'],
        'id': value['id'],
        'time': ((value['time']).toISOString()),
        'consumer': MemberToJSON(value['consumer']),
        'event': EventToJSON(value['event']),
    };
}

