/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventCreate
 */
export interface EventCreate {
    /**
     * 
     * @type {string}
     * @memberof EventCreate
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof EventCreate
     */
    startTime: Date;
    /**
     * 
     * @type {string}
     * @memberof EventCreate
     */
    location: string | null;
    /**
     * 
     * @type {number}
     * @memberof EventCreate
     */
    duration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EventCreate
     */
    authorId: number | null;
}

/**
 * Check if a given object implements the EventCreate interface.
 */
export function instanceOfEventCreate(value: object): value is EventCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    return true;
}

export function EventCreateFromJSON(json: any): EventCreate {
    return EventCreateFromJSONTyped(json, false);
}

export function EventCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'startTime': (new Date(json['start_time'])),
        'location': json['location'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'authorId': json['author_id'],
    };
}

  export function EventCreateToJSON(json: any): EventCreate {
      return EventCreateToJSONTyped(json, false);
  }

  export function EventCreateToJSONTyped(value?: EventCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'start_time': ((value['startTime']).toISOString()),
        'location': value['location'],
        'duration': value['duration'],
        'author_id': value['authorId'],
    };
}

