/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuoteCreate
 */
export interface QuoteCreate {
    /**
     * 
     * @type {string}
     * @memberof QuoteCreate
     */
    quote: string;
    /**
     * 
     * @type {Date}
     * @memberof QuoteCreate
     */
    date: Date | null;
    /**
     * 
     * @type {string}
     * @memberof QuoteCreate
     */
    location: string | null;
    /**
     * 
     * @type {number}
     * @memberof QuoteCreate
     */
    authorId: number;
}

/**
 * Check if a given object implements the QuoteCreate interface.
 */
export function instanceOfQuoteCreate(value: object): value is QuoteCreate {
    if (!('quote' in value) || value['quote'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    return true;
}

export function QuoteCreateFromJSON(json: any): QuoteCreate {
    return QuoteCreateFromJSONTyped(json, false);
}

export function QuoteCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuoteCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'quote': json['quote'],
        'date': (json['date'] == null ? null : new Date(json['date'])),
        'location': json['location'],
        'authorId': json['author_id'],
    };
}

  export function QuoteCreateToJSON(json: any): QuoteCreate {
      return QuoteCreateToJSONTyped(json, false);
  }

  export function QuoteCreateToJSONTyped(value?: QuoteCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quote': value['quote'],
        'date': (value['date'] == null ? null : (value['date'] as any).toISOString()),
        'location': value['location'],
        'author_id': value['authorId'],
    };
}

