/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Drink } from './Drink';
import {
    DrinkFromJSON,
    DrinkFromJSONTyped,
    DrinkToJSON,
    DrinkToJSONTyped,
} from './Drink';

/**
 * 
 * @export
 * @interface ResponseGetDrinksForEventEventsEventIdDrinksGet
 */
export interface ResponseGetDrinksForEventEventsEventIdDrinksGet {
}

/**
 * Check if a given object implements the ResponseGetDrinksForEventEventsEventIdDrinksGet interface.
 */
export function instanceOfResponseGetDrinksForEventEventsEventIdDrinksGet(value: object): value is ResponseGetDrinksForEventEventsEventIdDrinksGet {
    return true;
}

export function ResponseGetDrinksForEventEventsEventIdDrinksGetFromJSON(json: any): ResponseGetDrinksForEventEventsEventIdDrinksGet {
    return ResponseGetDrinksForEventEventsEventIdDrinksGetFromJSONTyped(json, false);
}

export function ResponseGetDrinksForEventEventsEventIdDrinksGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseGetDrinksForEventEventsEventIdDrinksGet {
    return json;
}

  export function ResponseGetDrinksForEventEventsEventIdDrinksGetToJSON(json: any): ResponseGetDrinksForEventEventsEventIdDrinksGet {
      return ResponseGetDrinksForEventEventsEventIdDrinksGetToJSONTyped(json, false);
  }

  export function ResponseGetDrinksForEventEventsEventIdDrinksGetToJSONTyped(value?: ResponseGetDrinksForEventEventsEventIdDrinksGet | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

