/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Drink } from './Drink';
import {
    DrinkFromJSON,
    DrinkFromJSONTyped,
    DrinkToJSON,
    DrinkToJSONTyped,
} from './Drink';

/**
 * 
 * @export
 * @interface ResponseGetDrinksForEventMembersMemberIdDrinksGet
 */
export interface ResponseGetDrinksForEventMembersMemberIdDrinksGet {
}

/**
 * Check if a given object implements the ResponseGetDrinksForEventMembersMemberIdDrinksGet interface.
 */
export function instanceOfResponseGetDrinksForEventMembersMemberIdDrinksGet(value: object): value is ResponseGetDrinksForEventMembersMemberIdDrinksGet {
    return true;
}

export function ResponseGetDrinksForEventMembersMemberIdDrinksGetFromJSON(json: any): ResponseGetDrinksForEventMembersMemberIdDrinksGet {
    return ResponseGetDrinksForEventMembersMemberIdDrinksGetFromJSONTyped(json, false);
}

export function ResponseGetDrinksForEventMembersMemberIdDrinksGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseGetDrinksForEventMembersMemberIdDrinksGet {
    return json;
}

  export function ResponseGetDrinksForEventMembersMemberIdDrinksGetToJSON(json: any): ResponseGetDrinksForEventMembersMemberIdDrinksGet {
      return ResponseGetDrinksForEventMembersMemberIdDrinksGetToJSONTyped(json, false);
  }

  export function ResponseGetDrinksForEventMembersMemberIdDrinksGetToJSONTyped(value?: ResponseGetDrinksForEventMembersMemberIdDrinksGet | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

