/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadChug
 */
export interface UploadChug {
    /**
     * 
     * @type {Array<string>}
     * @memberof UploadChug
     */
    id: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof UploadChug
     */
    time: Array<number>;
}

/**
 * Check if a given object implements the UploadChug interface.
 */
export function instanceOfUploadChug(value: object): value is UploadChug {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    return true;
}

export function UploadChugFromJSON(json: any): UploadChug {
    return UploadChugFromJSONTyped(json, false);
}

export function UploadChugFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadChug {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'time': json['time'],
    };
}

  export function UploadChugToJSON(json: any): UploadChug {
      return UploadChugToJSONTyped(json, false);
  }

  export function UploadChugToJSONTyped(value?: UploadChug | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'time': value['time'],
    };
}

